branches:
  only:
  - master
  - collisions
language: node_js
node_js:
- 10
script:
- scp -i ./2018_2_YetAnotherGame_id_rsa ./2018_2_YetAnotherGame ubuntu@95.163.215.234:/home/ubuntu/frontend2
before_install:
- openssl aes-256-cbc -K $encrypted_e7346fc74e21_key -iv $encrypted_e7346fc74e21_iv
  -in 2018_2_YetAnotherGame_id_rsa.pem.enc -out /home/denis/2018_2_YetAnotherGame/2018_2_YetAnotherGame_id_rsa.pem
  -d
